### PR TITLE
Unbreak build_toolchain_image

### PR DESCRIPTION
**Pull request by tobig**
This makes build_toolchain_image work as of today.

Unfortunately, it seems the resulting image does not work. 

Tests give:

```
$make test-jit-backend 
docker run -ti --rm -v /tmp:/tmp -v /home/grosser/Projects/pypyjs:/home/grosser/Projects/pypyjs -w /home/grosser/Projects/pypyjs -e "CFLAGS=$CFLAGS" -e "LDFLAGS=$LDFLAGS" -e "EMCFLAGS=$EMCFLAGS" -e "EMLDFLAGS=$EMLDFLAGS" -e "IN_DOCKER=1" -e "PYTHONPATH=$PYTHONPATH" 91f1ec8bcf73 python /home/grosser/Projects/pypyjs/deps/pypy/pytest.py --platform=emscripten -vx ./deps/pypy/rpython/jit/backend/asmjs
[version:WARNING] Errors getting Mercurial information: Not running from a Mercurial repository!
[platform:msg] Set platform with 'emscripten' cc=None, using cc='emcc', version='Unknown'
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.9 -- py-1.4.20 -- pytest-2.5.2 -- /usr/bin/python
pytest-2.5.2 from /home/grosser/Projects/pypyjs/deps/pypy/pytest.pyc
collecting 353 itemsMakefile:203: recipe for target 'test-jit-backend' failed
make: *** [test-jit-backend] Error 139
```
and "make release" gives:

```
$make release
cp ./build/pypyjs.vm.js ./lib/
python ./tools/extract_memory_initializer.py ./lib/pypyjs.vm.js
Traceback (most recent call last):
  File "./tools/extract_memory_initializer.py", line 44, in <module>
    raise ValueError("no memoryInitializer variable found")
ValueError: no memoryInitializer variable found
Makefile:68: recipe for target 'lib/pypyjs.vm.js' failed
make: *** [lib/pypyjs.vm.js] Error 1
```

Any idea what I missed?

### CODE REVIEW

**Comment by albertjan** [comment]
In newer versions of emscripten the memmory that can be allocated is moved to a separate file. It ends up next to pypy.vm.js and is called pypy.vm.mem.js or something allong those lines. If you mount you /var dicretory in docker you should be able to find it there. I'm traveling arm otherwise i'd been more exact. If you have a look at trinketapp/pypyjs makefile I've fixed it there. I think. But that is also an older emscripten so things may havr changed slightly. Goodluck! 😁

**Comment by tobig** [comment]
@albertjan: Thank you for the reply. There are many branches in trinketapp/pypyjs. The main branch does not have any commits over the official pypyjs repo. In some of the other branches you drop the call to extract_memory_initializer.py, but I did not find any other related changes.

In general, it seems support for an explicit memory init file is on purpose disabled: "--memory-init-file 0", because it seems to break running some stuff in the docker container. Not sure exactly why.

Also, did the tests ever work for you?

If you could point me to the branch you have been using, I would appreciate very much a pointer.

**Comment by albertjan** [comment]
Of the top of my head I think it's called 'emterpreter-es6' the branch. The tests definitelly passed last I built it. Last year or so. Yeah I drop the call to that script because the mem file is already sepperate.

**Comment by albertjan** [comment]
Did you get this to work?

**Comment by tobig** [comment]
Not the way I expected. I now just copy the build/pypyjs.vm.js file to an existing pypyjs-release/lib/pypy.vm.js directory and executing this one seems to work. A couple of things surprise me:

1) The name changed from pypy.vm.js to pypyjs.vm.js

No idea when this naming change happened.

2) You talk about that in your configuration pypy would create a separate .mem file

I cannot find such a file and do not see how this would be generated if '--memory-init-file 0' is used. We set this flag explicitly.

3) If I use "--memory-init-file 1" my build breaks with the type error similar to the one when setting "BINARYEN=1":

[platform:WARNING] INFO:root: - ok
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "./deps/pypy/rpython/bin/rpython", line 20, in <module>
    main()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/translator/goal/translate.py", line 217, in main
    targetspec_dic, translateconfig, config, args = parse_options_and_load_target()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/translator/goal/translate.py", line 156, in parse_options_and_load_target
    targetspec_dic = load_target(targetspec)
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/translator/goal/translate.py", line 98, in load_target
    mod = __import__(specname)
  File "./deps/pypy/pypy/goal/targetpypystandalone.py", line 13, in <module>
    from rpython.rlib import rthread
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rlib/rthread.py", line 1, in <module>
    from rpython.rtyper.lltypesystem import rffi, lltype, llmemory
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/lltypesystem/rffi.py", line 552, in <module>
    NUMBER_TYPES = setup()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/lltypesystem/rffi.py", line 541, in setup
    names = populate_inttypes()
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/lltypesystem/rffi.py", line 535, in populate_inttypes
    platform.populate_inttypes(populatelist)
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/tool/rfficache.py", line 83, in populate_inttypes
    sizes = sizeof_c_types(names_c, **kwds)
  File "/home/grosser/Projects/pypyjs/deps/pypy/rpython/rtyper/tool/rfficache.py", line 47, in sizeof_c_types
    assert len(lines) == len(typenames_c)
AssertionError

**Comment by albertjan** [comment]
It used to be called pypy.vm.js and it was renamed to pypyjs.vm.js a while ago. https://github.com/pypyjs/pypyjs/commit/22983cca30531c60474a092af0d6224ae2fb0d2a So that got reverted somehow.

**Comment by albertjan** [comment]
I think I used to get a separate memory file because I used emterpreter.

**Comment by tobig** [comment]
Sounds interesting. How did the emterpreter work for you? Did this reduce the startup cost?

**Comment by albertjan** [comment]
no, it didn't 😄 but did allow me to do `sleep`'s size is quite a bit bigger and all emterpreter paths were a lot slower. you can see a running example here.  https://trinket.io/pypyjs/d41d8cd98f00b204e9800998ecf8427e

As you can see the browser still yanks for a good few seconds parsing the js.

**Comment by tobig** [comment]
I get a page not found for above link.

**Comment by albertjan** [comment]
I great 😄 there's bug. https://trinket.io/pypyjs if you go there and enter this program and press run you should see it work.

```from time import sleep

def test():
  sleep(1)
  

print "start"
test()
print "stop"```

**Comment by tobig** [comment]
After also importing sleep from 'time' this works. Very interesting.

Btw, how did you implement your auto-completion. Did you manage to run jedi in pypyjs?

**Comment by albertjan** [comment]
@tobig I'm not entirely sure what we use. But it's not on the client, the code is sent to the server via a web socket and  that responds with the completion options.

**Comment by rfk** [comment]
Thanks @tobig!  This all looks good so I'm going to merge it and try it out on my machine.

**Pull request merged**
