### PR TITLE
Consolidate naming of things to "PyPy.js" in text and "pypyjs" in code.

### LINKED ISSUE #147: pypyjs / PyPyJS / PyPy-JS / PyPy.js ...
I know, a kind of a nonsense question...

What's the "official" spelling ???

Every time I write pypy, i have to think about the right spelling ;)

### PR DESCRIPTION
**Pull request by rfk**
Fixes #147.

@jedie @crantila here's a first attempt at simplifying some of the naming weirdness we've got going on in the project at the moment.  I'm currently trying out a build to make sure I haven't broken anything.  Thoughts?

I'm not sure I like losing the capitalization in `new PyPyJS() => new pypyjs()` but I can live with it.  The rest of it I think is definitely an improvement.

### CODE REVIEW

**Comment by crantila** [comment]
It looks good to me. I agree ``new pypyjs()`` isn't the best, but maybe that's a small price to pay for the consistency.

Thanks for asking, and renaming!

**Comment by rfk** [comment]
> I agree new pypyjs() isn't the best

I'm wondering if this is an opportunity to move away from the explicit "create a vm" model towards something that's simpler for default use-cases.  We could have an implicit, lazily-initialized default vm that you can just start using, like this:

```
    pypyjs = require("pypyjs.js") // or whatever in browser
    pypyjs.exec("print 'hello world'")
```

But if you want to create independent vms because e.g. you need control over runtime configuration, we can offer a convenience method like:

```
    var vm = pypyjs.createVM({ ...custom options here...})
    vm.exec("print 'hello world'")
```

**Comment by rfk** [comment]
(Like how hardly anyone creates instances of `random.Random` in python, but just uses the default instance with its sensible default behaviour)

**Comment by crantila** [comment]
That seems like it solves two problems!

Is there ever a situation where somebody would want to load ``pypyjs.js`` without creating an interpreter instance? I'm thinking not. And what happens to the initial VM when someone calls ``createVM()``? Maybe the answers are obvious, but I'm still quite new to The World of JavaScript.

**Comment by jedie** [comment]
> Maybe the answers are obvious, but I'm still quite new to The World of JavaScript.

Me, too. I don't know the "best practice" here...

**Comment by rfk** [comment]
OK, updated to make the top-level `pypyjs` name behave like a default interpreter instance.  Behind-the-scenes this actually loads a default VM lazily on demand.  So if you call `pypyjs.exec` then it'll Just Work, but if you always instantiate it via `new pypyjs()` then you won't pay the overhead of creating the default instance.

I ended up keeping `new pypyjs()` rather than `pypyjs.createVM()` because it didn't seem to make much difference once you don't have to do it by default.

**Comment by rfk** [comment]
I'm pretty happy with the feel of this overall, I'll go ahead and merge and cut that new release.

**Pull request merged**
