### PR TITLE
Refactor: top_leveL_scope is a module object

### PR DESCRIPTION
**Pull request by crantila**
As per issue #161. This fix seems to work for every situation I can think of.

### CODE REVIEW

**Comment by crantila** [comment]
Do you think I should add ``"__main__"`` to the list of built-in modules in the "module_bundler" script?

**Comment by rfk** [comment]
Looks good, thanks!

**Comment by rfk** [comment]
>  add "__main__" to the list of built-in modules in the "module_bundler" script?

Good idea, I went ahead and did this in https://github.com/pypyjs/pypyjs/commit/f409f5b30a154bc4d5a7509ede885cf5c64e6fae

**Comment by albertjan** [comment]
very cool this got merged! thanks @crantila @rfk

**Comment by crantila** [comment]
Thanks for merging, @rfk. I'll prepare a PR to get ``unittest`` to run&mdash;it's not much, actually!

**Pull request merged**
