### PR TITLE
Squashed commit of 'editor' branch

### PR DESCRIPTION
**Pull request by jedie**
origin: https://github.com/rfk/pypyjs/pull/102

EDIT: remove long commit list

### CODE REVIEW

**Comment by jedie** [comment]
https://github.com/jedie/pypyjs/commit/b4d60fa52da1459a61f6ca8e22ed493398dddff1 contains the "merge code parts": https://github.com/jedie/pypyjs/compare/458691bd8f...88f4299d67

**Comment by jedie** [comment]
Update this pull request to https://github.com/jedie/pypyjs/commit/dd27759528a8204dbb7a03147e3b8f59fa028d00

**Comment by jedie** [comment]
What's about a merge?

**Comment by rfk** [comment]
Hi @jedie, sorry for the delay, things have been pretty busy at work this week so I haven't had a lot of spare headspace to cycle back to things here.

I want to try to open up the project a bit, so I've made a pypyjs org into which I plan to transfer these repos: https://github.com/pypyjs

I'm currently thinking that it makes sense to split up the repos like so:
 * the existing `pypy` repo
 * the existing `pypyjs` repo, minus website
 * the website, in a `pypyjs.github.io` repo which can then be hosted on github pages
 * something like your https://github.com/jedie/pypyjs-source repo, for hosting release builds

What do you think?  I'd be happy to add you as collaborator to make it easier for you to keep hacking on this code.

**Comment by jedie** [comment]
Good idea!

**Comment by rfk** [comment]
OK, I've split out https://github.com/pypyjs/pypyjs.github.io as a separate repo, and it's live and running behind http://pypyjs.org.  I've also added experimental support for loading the pypy.js release files from a CDN.

Can you please rebase this against that repo?

**Comment by jedie** [comment]
I'm a little confused ;)

https://github.com/pypyjs/pypyjs is the main repro used for building PyPy.js, isn't it?
https://github.com/pypyjs/pypyjs.github.io is for pypyjs.org
https://github.com/pypyjs/pypyjs-release (and **-nojit**) contains the builded PyPy.js

OK. But we currently have the content of **/website/** in all of these repros.

What's about a cleanup:
* remove **/website/** from https://github.com/pypyjs/pypyjs and https://github.com/pypyjs/pypyjs.github.io
* include https://github.com/pypyjs/pypyjs-release (and **-nojit**) via git submpdules
* on built push the **/website/** to https://github.com/pypyjs/pypyjs-release

**Comment by jedie** [comment]
updated branch is online: https://github.com/pypyjs/pypyjs/compare/master...editor_squash

current --squash commit is: https://github.com/pypyjs/pypyjs/commit/465563b7aae4ee601a7d5b19ca5addbfb033822f

I also add the non-squashed branch here: https://github.com/pypyjs/pypyjs/compare/master...editor

**Comment by jedie** [comment]
I'm still little confused ;)

It makes not really sense to hold the website stuff in https://github.com/pypyjs/pypyjs and in https://github.com/pypyjs/pypyjs.github.io , too.

On the other side: We will run the unittests with the CDN links, if we include **pypyjs.github.io** as a submodule in **pypyjs**

And what i don't known:
* How PyPy.js will be build
* how the unittests can be run, after build
* how the external reprositories can be updated to a new build

So i don't know how the best practise looks like, related to all questions ;)

**Comment by rfk** [comment]
> It makes not really sense to hold the website stuff in https://github.com/pypyjs/pypyjs 
> and in https://github.com/pypyjs/pypyjs.github.io , too.

Indeed.  I meant to delete the "website" directly from https://github.com/pypyjs/pypyjs but didn't want to break the existing travis integration.

Here's what I'm thinking:

  * put all the website stuff in `pypyjs.github.io`, including the existing selenium tests and travis integration
  * continue to use the `pypyjs` repo and its Makefile for doing builds
  * add headless tests to the `pypyjs` repo, along the lines of https://github.com/pypyjs/pypyjs/blob/master/lib/tests/tests.js but done within a proper test framework of some kind
    * ideally we can run these under node, under the spidermonkey js shell, and in browser
  * add more scripting in `pypyjs` repo so that when we want to make a new release, it's a single command to:
    * build both jit and no-jit release bundles
    * upload them to github releases page for download
    * update the release submodule repos with the latest version, and tag them appropriately
    * and maybe additional steps that update the website semi-automatically?

Does the above make sense?  Will this make any part of the development flow harder than it is currently?  I want to avoid making things harder.

> * how the external reprositories can be updated to a new build

I'm not sure what you're asking here, if I didn't cover it above, can you please elaborate?

> So i don't know how the best practise looks like, related to all questions

Honestly, neither do I :-).  I think we'll have to try a few things out and see what works well and what doesn't.

**Comment by jedie** [comment]
>  I think we'll have to try a few things out and see what works well and what doesn't.

:+1:

**Comment by jedie** [comment]
It can be a little complicated, if changes in **/lib/pypy.js** should be made.

e.g.: the "load_status" branch, see: https://github.com/pypyjs/pypyjs/compare/load_status?expand=1#diff-64d4bc35610c5408957671ed3291a586

How should this be develop with the splitted repro?

I have not many experience with git submodules.

Maybe it's possible to switch to a new branch in the main repro (pypyjs.github.io) and the submodule (pypyjs-release) to made the "load_status" changes and test them separate from "master" ?

But this will result in two separate pull request, isn't it?

**Comment by jedie** [comment]
close this "editor" pull, because it's now here: https://github.com/pypyjs/pypyjs.github.io/issues/1

**Comment by rfk** [comment]
> It can be a little complicated, if changes in /lib/pypy.js should be made.

Indeed.  I think the right approach here is to do the changes in "pypyjs" repo first, with local tests in that repo.  Once we're happy with it, we can either just make a new release and update the website to use it, or do more testing in a branch of the website repo.

That will probably produce two pull requests but I think they could land one after the other, i.e. first make the changes the the pypy.js file and its local tests, then make the changes to the website code to use it.

If we can't land the change in that order, it's probably a sign of a layering violation and we should re-consider the change :-)

**Comment by jedie** [comment]
What's about to add to all repro README this:

----

Repository Overview

----

I already add this here:

* https://github.com/pypyjs/pypyjs.github.io/blob/master/README.rst#repository-overview

**Pull request closed without merging**
